programa: main.o log.o helpers.o
	gcc -o programa main.o log.o helpers.o

main.o: main.c
	gcc -c main.c

log.o: log.c log.h
	gcc -c log.c

helpers.o: helpers.c helpers.h
	gcc -c helpers.c

clean:
	rm -f programa *.o